# Generated by Django 3.1.7 on 2021-06-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isKilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isSaved',
            field=models.BooleanField(default=False),
        ),
    ]
