# Generated by Django 3.1.7 on 2021-06-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20210628_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isSaved',
        ),
    ]
